elasticsearch:
    image: elasticsearch:latest

logstash:
    image: logstash:latest
    ports:
        - 12201:12201/udp
    links:
        - elasticsearch
    volumes:
        - /cluster-elk:/config
    entrypoint:
        logstash -f /config/spring-gelf.conf

kibana:
    image: kibana:latest
    ports:
        - 5601:5601
    links:
        - elasticsearch

zipkin:
    image: openzipkin/zipkin:latest
    ports:
        - 9411:9411
